
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cmsapp
    username: root
    password: Diegotobon28
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    generate-ddl: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher