
spring:
  data:
    mongodb:
      uri: mongodb+srv://programadores-chile:programadores-chile@programadores-chile.oeo0udf.mongodb.net/?retryWrites=true&w=majority
      database: cms-app
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher